namespace Fantasm.Disassembler.Tests
{
    internal static class OpCodes
    {
        // Each row here corresponds to a line in the Intel manual
        public static OpCodeProperties[] All =
        {
            new OpCodeProperties(0x37, Instruction.Aaa, OperandFormat.None, Compatibility.Invalid64),
            new OpCodeProperties(0xD5, Instruction.Aad, OperandFormat.Ib, Compatibility.Invalid64),
            new OpCodeProperties(0xD4, Instruction.Aam, OperandFormat.Ib, Compatibility.Invalid64),
            new OpCodeProperties(0x3F, Instruction.Aas, OperandFormat.None, Compatibility.Invalid64),

            new OpCodeProperties(0x14, Instruction.Adc, OperandFormat.AL, OperandFormat.Ib),
            new OpCodeProperties(0x15, Instruction.Adc, OperandSize.Size16, OperandFormat.AX, OperandFormat.Iw),
            new OpCodeProperties(0x15, Instruction.Adc, OperandSize.Size32, OperandFormat.EAX, OperandFormat.Id),
            new OpCodeProperties(RexPrefix.W, 0x15, Instruction.Adc, OperandFormat.RAX, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x80, 2, Instruction.Adc, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x80, 2, Instruction.Adc, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 2, Instruction.Adc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Iw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 2, Instruction.Adc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x81, 2, Instruction.Adc, OperandFormat.Eq, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 2, Instruction.Adc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 2, Instruction.Adc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x83, 2, Instruction.Adc, OperandFormat.Eq, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x10, Instruction.Adc, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x10, Instruction.Adc, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x11, Instruction.Adc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x11, Instruction.Adc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x11, Instruction.Adc, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(0x12, Instruction.Adc, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(RexPrefix.W, 0x12, Instruction.Adc, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(0x13, Instruction.Adc, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(0x13, Instruction.Adc, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, 0x13, Instruction.Adc, OperandFormat.Gq, OperandFormat.Eq),

            new OpCodeProperties(0x04, Instruction.Add, OperandFormat.AL, OperandFormat.Ib),
            new OpCodeProperties(0x05, Instruction.Add, OperandSize.Size16, OperandFormat.AX, OperandFormat.Iw),
            new OpCodeProperties(0x05, Instruction.Add, OperandSize.Size32, OperandFormat.EAX, OperandFormat.Id),
            new OpCodeProperties(RexPrefix.W, 0x05, Instruction.Add, OperandFormat.RAX, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x80, 0, Instruction.Add, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x80, 0, Instruction.Add, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 0, Instruction.Add, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Iw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 0, Instruction.Add, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x81, 0, Instruction.Add, OperandFormat.Eq, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 0, Instruction.Add, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 0, Instruction.Add, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x83, 0, Instruction.Add, OperandFormat.Eq, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x00, Instruction.Add, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x0, Instruction.Add, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x01, Instruction.Add, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x01, Instruction.Add, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x01, Instruction.Add, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(0x02, Instruction.Add, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(RexPrefix.W, 0x02, Instruction.Add, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(0x03, Instruction.Add, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(0x03, Instruction.Add, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, 0x03, Instruction.Add, OperandFormat.Gq, OperandFormat.Eq),

            new OpCodeProperties(0x24, Instruction.And, OperandFormat.AL, OperandFormat.Ib),
            new OpCodeProperties(0x25, Instruction.And, OperandSize.Size16, OperandFormat.AX, OperandFormat.Iw),
            new OpCodeProperties(0x25, Instruction.And, OperandSize.Size32, OperandFormat.EAX, OperandFormat.Id),
            new OpCodeProperties(RexPrefix.W, 0x25, Instruction.And, OperandFormat.RAX, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x80, 4, Instruction.And, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x80, 4, Instruction.And, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 4, Instruction.And, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Iw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x81, 4, Instruction.And, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x81, 4, Instruction.And, OperandFormat.Eq, OperandFormat.Id),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 4, Instruction.And, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x83, 4, Instruction.And, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x83, 4, Instruction.And, OperandFormat.Eq, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x20, Instruction.And, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x20, Instruction.And, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x21, Instruction.And, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, 0x21, Instruction.And, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0x21, Instruction.And, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(0x22, Instruction.And, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(RexPrefix.W, 0x22, Instruction.And, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(0x23, Instruction.And, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(0x23, Instruction.And, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, 0x23, Instruction.And, OperandFormat.Gq, OperandFormat.Eq),

            new OpCodeProperties(0x63, Instruction.Arpl, OperandFormat.Ew, OperandFormat.Gw, Compatibility.NotEncodable64),

            new OpCodeProperties(0x62, Instruction.Bound, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew, Compatibility.Invalid64),
            new OpCodeProperties(0x62, Instruction.Bound, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed, Compatibility.Invalid64),

            new OpCodeProperties(new byte[] { 0x0F, 0xBC }, Instruction.Bsf, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(new byte[] { 0x0F, 0xBC }, Instruction.Bsf, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xBC }, Instruction.Bsf, OperandFormat.Gq, OperandFormat.Eq),

            new OpCodeProperties(new byte[] { 0x0F, 0xBD }, Instruction.Bsr, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(new byte[] { 0x0F, 0xBD }, Instruction.Bsr, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xBD }, Instruction.Bsr, OperandFormat.Gq, OperandFormat.Eq),

            // expanded from intel table
            new OpCodeProperties(new byte[] { 0x0F, 0xC8 }, Instruction.Bswap, Register.Eax),
            new OpCodeProperties(new byte[] { 0x0F, 0xC9 }, Instruction.Bswap, Register.Ecx),
            new OpCodeProperties(new byte[] { 0x0F, 0xCA }, Instruction.Bswap, Register.Edx),
            new OpCodeProperties(new byte[] { 0x0F, 0xCB }, Instruction.Bswap, Register.Ebx),
            new OpCodeProperties(new byte[] { 0x0F, 0xCC }, Instruction.Bswap, Register.Esp),
            new OpCodeProperties(new byte[] { 0x0F, 0xCD }, Instruction.Bswap, Register.Ebp),
            new OpCodeProperties(new byte[] { 0x0F, 0xCE }, Instruction.Bswap, Register.Esi),
            new OpCodeProperties(new byte[] { 0x0F, 0xCF }, Instruction.Bswap, Register.Edi),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xC8 }, Instruction.Bswap, Register.Rax),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xC9 }, Instruction.Bswap, Register.Rcx),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCA }, Instruction.Bswap, Register.Rdx),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCB }, Instruction.Bswap, Register.Rbx),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCC }, Instruction.Bswap, Register.Rsp),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCD }, Instruction.Bswap, Register.Rbp),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCE }, Instruction.Bswap, Register.Rsi),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xCF }, Instruction.Bswap, Register.Rdi),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xC8 }, Instruction.Bswap, Register.R8D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xC9 }, Instruction.Bswap, Register.R9D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCA }, Instruction.Bswap, Register.R10D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCB }, Instruction.Bswap, Register.R11D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCC }, Instruction.Bswap, Register.R12D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCD }, Instruction.Bswap, Register.R13D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCE }, Instruction.Bswap, Register.R14D),
            new OpCodeProperties(RexPrefix.B, new byte[] { 0x0F, 0xCF }, Instruction.Bswap, Register.R15D),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xC8 }, Instruction.Bswap, Register.R8),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xC9 }, Instruction.Bswap, Register.R9),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCA }, Instruction.Bswap, Register.R10),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCB }, Instruction.Bswap, Register.R11),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCC }, Instruction.Bswap, Register.R12),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCD }, Instruction.Bswap, Register.R13),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCE }, Instruction.Bswap, Register.R14),
            new OpCodeProperties(RexPrefix.W | RexPrefix.B, new byte[] { 0x0F, 0xCF }, Instruction.Bswap, Register.R15),

            new OpCodeProperties(new byte[] { 0x0F, 0xA3 }, Instruction.Bt, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0xA3 }, Instruction.Bt, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xA3 }, Instruction.Bt, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0xBA }, 4, Instruction.Bt, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(new byte[] { 0x0F, 0xBA }, 4, Instruction.Bt, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0xBA }, 4, Instruction.Bt, OperandFormat.Eq, OperandFormat.Ib),

            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBB }, Instruction.Btc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBB }, Instruction.Btc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xBB }, Instruction.Btc, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 7, Instruction.Btc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 7, Instruction.Btc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xBA }, 7, Instruction.Btc, OperandFormat.Eq, OperandFormat.Ib),

            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xB3 }, Instruction.Btr, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xB3 }, Instruction.Btr, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xB3 }, Instruction.Btr, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 6, Instruction.Btr, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 6, Instruction.Btr, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xBA }, 6, Instruction.Btr, OperandFormat.Eq, OperandFormat.Ib),

            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xAB }, Instruction.Bts, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xAB }, Instruction.Bts, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xAB }, Instruction.Bts, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 5, Instruction.Bts, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xBA }, 5, Instruction.Bts, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xBA }, 5, Instruction.Bts, OperandFormat.Eq, OperandFormat.Ib),

            new OpCodeProperties(0xE8, Instruction.Call, OperandSize.Size16, OperandFormat.Jw, Compatibility.NotEncodable64),
            new OpCodeProperties(0xE8, Instruction.Call, OperandSize.Size32, OperandFormat.Jd),
            new OpCodeProperties(0xFF, 2, Instruction.Call, OperandSize.Size16, OperandFormat.Ew, Compatibility.NotEncodable64),
            new OpCodeProperties(0xFF, 2, Instruction.Call, OperandSize.Size32, OperandFormat.Ed, Compatibility.NotEncodable64),
            new OpCodeProperties(0xFF, 2, Instruction.Call, OperandFormat.Eq, Compatibility.NotEncodable32),
            new OpCodeProperties(0x9A, Instruction.CallFar, OperandSize.Size16, OperandFormat.Aww, Compatibility.Invalid64),
            new OpCodeProperties(0x9A, Instruction.CallFar, OperandSize.Size32, OperandFormat.Awd, Compatibility.Invalid64),
            new OpCodeProperties(0xFF, 3, Instruction.CallFar, OperandSize.Size16, OperandFormat.Mw),
            new OpCodeProperties(0xFF, 3, Instruction.CallFar, OperandSize.Size32, OperandFormat.Md, Compatibility.NotEncodable64),
            new OpCodeProperties(0xFF, 3, Instruction.CallFar, OperandFormat.Mq, Compatibility.NotEncodable32),
            new OpCodeProperties(RexPrefix.W, 0xFF, 3, Instruction.CallFar, OperandFormat.Mq),

            new OpCodeProperties(0x98, Instruction.Cbw, OperandSize.Size16),
            new OpCodeProperties(0x98, Instruction.Cwde, OperandSize.Size32),
            new OpCodeProperties(RexPrefix.W, 0x98, Instruction.Cdqe),

            new OpCodeProperties(0xF8, Instruction.Clc),

            new OpCodeProperties(0xFC, Instruction.Cld),

            new OpCodeProperties(0xFA, Instruction.Cli),

            new OpCodeProperties(new byte[] { 0x0f, 0x06 }, Instruction.Clts),

            new OpCodeProperties(0xF5, Instruction.Cmc),

            new OpCodeProperties(new byte[] { 0x0F, 0x47 }, Instruction.Cmova, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x47 }, Instruction.Cmova, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x47 }, Instruction.Cmova, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovae, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovae, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x43 }, Instruction.Cmovae, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovb, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovb, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x42 }, Instruction.Cmovb, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x46 }, Instruction.Cmovbe, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x46 }, Instruction.Cmovbe, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x46 }, Instruction.Cmovbe, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x42 }, Instruction.Cmovc, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x44 }, Instruction.Cmove, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x44 }, Instruction.Cmove, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x44 }, Instruction.Cmove, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4F }, Instruction.Cmovg, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4F }, Instruction.Cmovg, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4F }, Instruction.Cmovg, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4D }, Instruction.Cmovge, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4D }, Instruction.Cmovge, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4D }, Instruction.Cmovge, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4C }, Instruction.Cmovl, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4C }, Instruction.Cmovl, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4C }, Instruction.Cmovl, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4E }, Instruction.Cmovle, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4E }, Instruction.Cmovle, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4E }, Instruction.Cmovle, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x46 }, Instruction.Cmovna, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x46 }, Instruction.Cmovna, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x46 }, Instruction.Cmovna, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovnae, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x42 }, Instruction.Cmovnae, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x42 }, Instruction.Cmovnae, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovnb, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovnb, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x43 }, Instruction.Cmovnb, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x47 }, Instruction.Cmovnbe, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x47 }, Instruction.Cmovnbe, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x47 }, Instruction.Cmovnbe, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovnc, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x43 }, Instruction.Cmovnc, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x43 }, Instruction.Cmovnc, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x45 }, Instruction.Cmovne, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x45 }, Instruction.Cmovne, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x45 }, Instruction.Cmovne, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4E }, Instruction.Cmovng, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4E }, Instruction.Cmovng, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4E }, Instruction.Cmovng, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4C }, Instruction.Cmovnge, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4C }, Instruction.Cmovnge, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4C }, Instruction.Cmovnge, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4D }, Instruction.Cmovnl, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4D }, Instruction.Cmovnl, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4D }, Instruction.Cmovnl, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4F }, Instruction.Cmovnle, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4F }, Instruction.Cmovnle, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4F }, Instruction.Cmovnle, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x41 }, Instruction.Cmovno, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x41 }, Instruction.Cmovno, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x41 }, Instruction.Cmovno, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4B }, Instruction.Cmovnp, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4B }, Instruction.Cmovnp, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4B }, Instruction.Cmovnp, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x49 }, Instruction.Cmovns, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x49 }, Instruction.Cmovns, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x49 }, Instruction.Cmovns, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x45 }, Instruction.Cmovnz, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x45 }, Instruction.Cmovnz, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x45 }, Instruction.Cmovnz, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x40 }, Instruction.Cmovo, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x40 }, Instruction.Cmovo, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x40 }, Instruction.Cmovo, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4A }, Instruction.Cmovp, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4A }, Instruction.Cmovp, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4A }, Instruction.Cmovp, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4A }, Instruction.Cmovpe, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4A }, Instruction.Cmovpe, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4A }, Instruction.Cmovpe, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x4B }, Instruction.Cmovpo, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x4B }, Instruction.Cmovpo, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x4B }, Instruction.Cmovpo, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x48 }, Instruction.Cmovs, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x48 }, Instruction.Cmovs, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x48 }, Instruction.Cmovs, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(new byte[] { 0x0F, 0x44 }, Instruction.Cmovz, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(new byte[] { 0x0F, 0x44 }, Instruction.Cmovz, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, new byte[] { 0x0F, 0x44 }, Instruction.Cmovz, OperandFormat.Eq, OperandFormat.Gq),

            new OpCodeProperties(0x3C, Instruction.Cmp, OperandFormat.AL, OperandFormat.Ib),
            new OpCodeProperties(0x3D, Instruction.Cmp, OperandSize.Size16, OperandFormat.AX, OperandFormat.Iw),
            new OpCodeProperties(0x3D, Instruction.Cmp, OperandSize.Size32, OperandFormat.EAX, OperandFormat.Id),
            new OpCodeProperties(RexPrefix.W, 0x3D, Instruction.Cmp, OperandFormat.RAX, OperandFormat.Id),
            new OpCodeProperties(0x80, 7, Instruction.Cmp, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(RexPrefix.W, 0x80, 7, Instruction.Cmp, OperandFormat.Eb, OperandFormat.Ib),
            new OpCodeProperties(0x81, 7, Instruction.Cmp, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Iw),
            new OpCodeProperties(0x81, 7, Instruction.Cmp, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Id),
            new OpCodeProperties(RexPrefix.W, 0x81, 7, Instruction.Cmp, OperandFormat.Eq, OperandFormat.Id),
            new OpCodeProperties(0x83, 7, Instruction.Cmp, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Ib),
            new OpCodeProperties(0x83, 7, Instruction.Cmp, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Ib),
            new OpCodeProperties(RexPrefix.W, 0x83, 7, Instruction.Cmp, OperandFormat.Eq, OperandFormat.Ib),
            new OpCodeProperties(0x38, Instruction.Cmp, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(RexPrefix.W, 0x38, Instruction.Cmp, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(0x39, Instruction.Cmp, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(0x39, Instruction.Cmp, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(RexPrefix.W, 0x39, Instruction.Cmp, OperandFormat.Eq, OperandFormat.Gq),
            new OpCodeProperties(0x3A, Instruction.Cmp, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(RexPrefix.W, 0x3A, Instruction.Cmp, OperandFormat.Gb, OperandFormat.Eb),
            new OpCodeProperties(0x3B, Instruction.Cmp, OperandSize.Size16, OperandFormat.Gw, OperandFormat.Ew),
            new OpCodeProperties(0x3B, Instruction.Cmp, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, 0x3B, Instruction.Cmp, OperandFormat.Gq, OperandFormat.Eq),

            new OpCodeProperties(0xA6, Instruction.Cmpsb),
            new OpCodeProperties(0xA7, Instruction.Cmpsw, OperandSize.Size16),
            new OpCodeProperties(0xA7, Instruction.Cmpsd, OperandSize.Size32),
            new OpCodeProperties(RexPrefix.W, 0xA7, Instruction.Cmpsq),

            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xB0 }, Instruction.Cmpxchg, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xB0 }, Instruction.Cmpxchg, OperandFormat.Eb, OperandFormat.Gb),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xB1 }, Instruction.Cmpxchg, OperandSize.Size16, OperandFormat.Ew, OperandFormat.Gw),
            new OpCodeProperties(InstructionPrefixes.Lock, new byte[] { 0x0F, 0xB1 }, Instruction.Cmpxchg, OperandSize.Size32, OperandFormat.Ed, OperandFormat.Gd),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xB1 }, Instruction.Cmpxchg, OperandFormat.Eq, OperandFormat.Gq),

            new OpCodeProperties(new byte[] { 0x0F, 0xC7 }, 1, Instruction.Cmpxchg8b, OperandFormat.Mq, InstructionPrefixes.Lock),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, new byte[] { 0x0F, 0xC7 }, 1, Instruction.Cmpxchg16b, OperandFormat.Mdq),

            new OpCodeProperties(new byte[] { 0x0F, 0xA2 }, Instruction.Cpuid, OperandFormat.None),

            new OpCodeProperties(InstructionPrefixes.RepNZ, new byte[] { 0x0F, 0x38, 0xF0 }, Instruction.Crc32, OperandFormat.Gd, OperandFormat.Eb),
            new OpCodeProperties(InstructionPrefixes.RepNZ, (RexPrefix)0, new byte[] { 0x0F, 0x38, 0xF0 }, Instruction.Crc32, OperandFormat.Gd, OperandFormat.Eb),
            new OpCodeProperties(InstructionPrefixes.RepNZ, new byte[] { 0x0F, 0x38, 0xF1 }, Instruction.Crc32, OperandSize.Size16, OperandFormat.Gd, OperandFormat.Ew),
            new OpCodeProperties(InstructionPrefixes.RepNZ, new byte[] { 0x0F, 0x38, 0xF1 }, Instruction.Crc32, OperandSize.Size32, OperandFormat.Gd, OperandFormat.Ed),
            new OpCodeProperties(InstructionPrefixes.RepNZ, RexPrefix.W, new byte[] { 0x0F, 0x38, 0xF0 }, Instruction.Crc32, OperandFormat.Gd, OperandFormat.Eb),
            new OpCodeProperties(InstructionPrefixes.RepNZ, RexPrefix.W, new byte[] { 0x0F, 0x38, 0xF1 }, Instruction.Crc32, OperandFormat.Gd, OperandFormat.Eq),

            new OpCodeProperties(0x99, Instruction.Cwd, OperandSize.Size16, OperandFormat.None),
            new OpCodeProperties(0x99, Instruction.Cdq, OperandSize.Size32, OperandFormat.None),
            new OpCodeProperties(RexPrefix.W, 0x99, Instruction.Cqo, OperandFormat.None),

            new OpCodeProperties(0x27, Instruction.Daa, OperandFormat.None, Compatibility.Invalid64),

            new OpCodeProperties(0x2F, Instruction.Das, OperandFormat.None, Compatibility.Invalid64),

            new OpCodeProperties(InstructionPrefixes.Lock, 0xFE, 1, Instruction.Dec, OperandFormat.Eb),
            new OpCodeProperties(InstructionPrefixes.Lock, (RexPrefix)0, 0xFE, 1, Instruction.Dec, OperandFormat.Eb),
            new OpCodeProperties(InstructionPrefixes.Lock, 0xFF, 1, Instruction.Dec, OperandSize.Size16, OperandFormat.Ew),
            new OpCodeProperties(InstructionPrefixes.Lock, 0xFF, 1, Instruction.Dec, OperandSize.Size32, OperandFormat.Ed),
            new OpCodeProperties(InstructionPrefixes.Lock, RexPrefix.W, 0xFF, 1, Instruction.Dec, OperandFormat.Eq),
            // expanded from intel table
            new OpCodeProperties(0x48, Instruction.Dec, OperandSize.Size16, Register.Ax, Compatibility.NotEncodable64),
            new OpCodeProperties(0x49, Instruction.Dec, OperandSize.Size16, Register.Cx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4A, Instruction.Dec, OperandSize.Size16, Register.Dx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4B, Instruction.Dec, OperandSize.Size16, Register.Bx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4C, Instruction.Dec, OperandSize.Size16, Register.Sp, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4D, Instruction.Dec, OperandSize.Size16, Register.Bp, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4E, Instruction.Dec, OperandSize.Size16, Register.Si, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4F, Instruction.Dec, OperandSize.Size16, Register.Di, Compatibility.NotEncodable64),
            new OpCodeProperties(0x48, Instruction.Dec, OperandSize.Size32, Register.Eax, Compatibility.NotEncodable64),
            new OpCodeProperties(0x49, Instruction.Dec, OperandSize.Size32, Register.Ecx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4A, Instruction.Dec, OperandSize.Size32, Register.Edx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4B, Instruction.Dec, OperandSize.Size32, Register.Ebx, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4C, Instruction.Dec, OperandSize.Size32, Register.Esp, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4D, Instruction.Dec, OperandSize.Size32, Register.Ebp, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4E, Instruction.Dec, OperandSize.Size32, Register.Esi, Compatibility.NotEncodable64),
            new OpCodeProperties(0x4F, Instruction.Dec, OperandSize.Size32, Register.Edi, Compatibility.NotEncodable64),

            new OpCodeProperties(0xF6, 6, Instruction.Div, OperandFormat.Eb),
            new OpCodeProperties((RexPrefix)0, 0xF6, 6, Instruction.Div, OperandFormat.Eb),
            new OpCodeProperties(0xF7, 6, Instruction.Div, OperandSize.Size16, OperandFormat.Ew),
            new OpCodeProperties(0xF7, 6, Instruction.Div, OperandSize.Size32, OperandFormat.Ed),
            new OpCodeProperties(RexPrefix.W, 0xF7, 6, Instruction.Div, OperandFormat.Eq),

            new OpCodeProperties(new byte[] { 0x0f, 0x77 }, Instruction.Emms, OperandFormat.None),

            new OpCodeProperties(0xC8, Instruction.Enter, OperandFormat.Iw, OperandFormat.Ib),

            new OpCodeProperties(0xF4, Instruction.Hlt),

        };
    }
}
